name: Build and deploy Node.js app to Azure Web App - webapp-fe-dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install, build, test
        run: |
          npm ci
          npm run build --if-present
          npm test --if-present

      - name: Upload artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: dist/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5E0BFAB0E752429E834A7CBDAA4712A6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E66F20DAF068496C8BD203CAF2051853 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D120BEFE516D4D3EACDC2907D500BB4E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: webapp-fe-dev
          slot-name: Production
          package: dist/
